/*
 * Board mapping aligned to SCH_Schematic1_1_2026-04-07.pdf and
 * ??_20260408(1).xlsx.
 *
 * Confirmed mappings from the schematic:
 * - CN3 card reader: USART1 on PA9/PA10
 * - 4G control: EC800_POWER on PC5, NET_PWRKEY on PB4
 * - RS485 sensor bus: USART2 on PA2/PA3, direction IO on PA1
 * - Battery detect: BAT_TEST enable on PB12, ACC analog sense on PA0
 *
 * The page-2 PNG text alignment for TX4/RX4/TX5/RX5 is visually ambiguous.
 * We follow the spreadsheet plus STM32F103 hardware UART pin mapping:
 * - UART4  -> PC10 / PC11
 * - UART5  -> PC12 / PD2
 */
#ifndef BOARD_HW_CONFIG_H
#define BOARD_HW_CONFIG_H

#define BOARD_HW_SCHEMATIC_FILE "SCH_Schematic1_1_2026-04-07.pdf"
#define BOARD_HW_MCU_PART_STR   "STM32F103RCT6"

#define BOARD_HW_MODEM_PART_STR "EC801ECNLE-N01-SNNSA"

#define BOARD_HW_USART_INSTANCE_CARD_READER 1
#define BOARD_HW_PIN_USART1_TX_PORT_A 9U
#define BOARD_HW_PIN_USART1_RX_PORT_A 10U

#define BOARD_HW_USART_INSTANCE_4G 4
#define BOARD_HW_PIN_UART4_TX_PORT_C 10U
#define BOARD_HW_PIN_UART4_RX_PORT_C 11U
#define BOARD_HW_PIN_NET_POWER_PORT_C 5U
#define BOARD_HW_PIN_NET_PWRKEY_PORT_B 4U

#define BOARD_HW_HAS_DUAL_SIM 1

#define BOARD_HW_RS485_ISOLATOR_STR "CA-IS3092W"
#define BOARD_HW_USART_INSTANCE_RS485 2
#define BOARD_HW_PIN_RS485_DIR_PORT_A 1U
#define BOARD_HW_PIN_USART2_TX_PORT_A 2U
#define BOARD_HW_PIN_USART2_RX_PORT_A 3U

#define BOARD_HW_I2C_INSTANCE_SENSOR 2
#define BOARD_HW_PIN_I2C2_SCL_PORT_B 10U
#define BOARD_HW_PIN_I2C2_SDA_PORT_B 11U

#define BOARD_HW_UART_PORT_CARD_READER BOARD_HW_USART_INSTANCE_CARD_READER

/* CN4 debug header is exposed as logical port 5. */
#define BOARD_HW_UART_PORT_CN4_DEBUG 5
#define BOARD_HW_UART_PORT_DEBUG     BOARD_HW_UART_PORT_CN4_DEBUG

#define BOARD_HW_LORA_MODULE_STR "Ra-01SC"
#define BOARD_HW_SPI_INSTANCE_LORA 1
#define BOARD_HW_PIN_SPI1_NSS_PORT_A 4U
#define BOARD_HW_PIN_SPI1_SCK_PORT_A 5U
#define BOARD_HW_PIN_SPI1_MISO_PORT_A 6U
#define BOARD_HW_PIN_SPI1_MOSI_PORT_A 7U

#define BOARD_HW_VOICE_IC_STR     "BSO615NV"
#define BOARD_HW_MOTOR_DRIVER_STR "AS4950"

#define BOARD_HW_PIN_ACC_PORT_A 0U
#define BOARD_HW_PIN_BAT_TEST_ENABLE_PORT_B 12U

/* Battery voltage is sampled on the ACC node after BAT_TEST enables Q4. */
#define BOARD_HW_ADC1_CHANNEL_BAT_TEST 0U
#define BOARD_HW_ADC_BAT_TEST_PORT_A_PIN 0U

#define BOARD_HW_ADC1_CHANNEL_ACC_ANALOG 0U
#define BOARD_HW_ADC1_CHANNEL_SOLAR_OR_MPPT 0xFFU

#define BOARD_HW_UART_PORT_MODEM_4G BOARD_HW_USART_INSTANCE_4G
#define BOARD_HW_UART_PORT_RS485    BOARD_HW_USART_INSTANCE_RS485

#endif /* BOARD_HW_CONFIG_H */
