/**
 * 硬件固定映射：SCH_Schematic1_1_2026-04-07.pdf（Board1_1）
 *
 * CN3：刷卡器，USART1（PA9 TX / PA10 RX）
 * CN4：USB-TTL 调试，PC12 / PD2（RCT6 无 UART5，固件用 GPIO 模拟 115200 发 TX；RX 占位）
 * RS485：USART3 PB10/PB11（U8）
 */
#ifndef BOARD_HW_CONFIG_H
#define BOARD_HW_CONFIG_H

#define BOARD_HW_SCHEMATIC_FILE "SCH_Schematic1_1_2026-04-07.pdf"
#define BOARD_HW_MCU_PART_STR   "STM32F103RCT6"

#define BOARD_HW_MODEM_PART_STR "EC801ECNLE-N01-SNNSA"

#define BOARD_HW_USART_INSTANCE_CARD_READER 1
#define BOARD_HW_PIN_USART1_TX_PORT_A 9U
#define BOARD_HW_PIN_USART1_RX_PORT_A 10U

#define BOARD_HW_USART_INSTANCE_4G 4
#define BOARD_HW_PIN_UART4_TX_PORT_C 10U
#define BOARD_HW_PIN_UART4_RX_PORT_C 11U
#define BOARD_HW_PIN_NET_PWRKEY_PORT_B 5U

#define BOARD_HW_HAS_DUAL_SIM 1

#define BOARD_HW_RS485_ISOLATOR_STR "CA-IS3092W"
#define BOARD_HW_USART_INSTANCE_RS485 3
#define BOARD_HW_PIN_USART3_TX_PORT_B 10U
#define BOARD_HW_PIN_USART3_RX_PORT_B 11U

/** CN3 刷卡：逻辑口 1，硬件 USART1 */
#define BOARD_HW_UART_PORT_CARD_READER BOARD_HW_USART_INSTANCE_CARD_READER

/**
 * CN4 TTL：逻辑口 4（非芯片硬件 USART 编号）。
 * PC12=TX、PD2=RX；F103RCT6 无 UART5，调试发送用 GPIO bit-bang。
 */
#define BOARD_HW_UART_PORT_CN4_DEBUG 5
#define BOARD_HW_UART_PORT_DEBUG     BOARD_HW_UART_PORT_CN4_DEBUG

#define BOARD_HW_PIN_USART2_TX_PORT_A 2U
#define BOARD_HW_PIN_USART2_RX_PORT_A 3U

#define BOARD_HW_LORA_MODULE_STR "Ra-01SC"
#define BOARD_HW_SPI_INSTANCE_LORA 1
#define BOARD_HW_PIN_SPI1_NSS_PORT_A 4U
#define BOARD_HW_PIN_SPI1_SCK_PORT_A 5U
#define BOARD_HW_PIN_SPI1_MISO_PORT_A 6U
#define BOARD_HW_PIN_SPI1_MOSI_PORT_A 7U

#define BOARD_HW_VOICE_IC_STR   "BSO615NV"
#define BOARD_HW_MOTOR_DRIVER_STR "AS4950"

/** ACC 网络 -> PA0（WKUP） */
#define BOARD_HW_PIN_ACC_PORT_A 0U

/** BAT_TEST -> PA1 = ADC1_IN1 */
#define BOARD_HW_ADC1_CHANNEL_BAT_TEST 1U
#define BOARD_HW_ADC_BAT_TEST_PORT_A_PIN 1U

#define BOARD_HW_ADC1_CHANNEL_ACC_ANALOG 0U

/** 太阳能未进 MCU ADC 时固定未使用 */
#define BOARD_HW_ADC1_CHANNEL_SOLAR_OR_MPPT 0xFFU

#define BOARD_HW_UART_PORT_MODEM_4G  BOARD_HW_USART_INSTANCE_4G
#define BOARD_HW_UART_PORT_RS485    BOARD_HW_USART_INSTANCE_RS485

#endif /* BOARD_HW_CONFIG_H */
