#ifndef SCAN_TRIAL_DEFS_H
#define SCAN_TRIAL_DEFS_H

#define SCAN_TRIAL_PROTOCOL_VERSION      "1.0.0"
#define SCAN_TRIAL_CONTROLLER_CODE       "scan_irrigation_controller_a01"
#define SCAN_TRIAL_CONTROLLER_ROLE       "scan_irrigation_controller"
#define SCAN_TRIAL_DEPLOYMENT_MODE       "standalone"
#define SCAN_TRIAL_CONTROLLER_NAME       "Scan Irrigation Controller A01"

#define SCAN_TRIAL_HARDWARE_VERSION_CODE "HW-SCAN-IRR-CTRL-4G-A01"
#define SCAN_TRIAL_HARDWARE_NAME         "Scan Irrigation Control A01"
#define SCAN_TRIAL_HARDWARE_SKU          "SCAN-IRR-CTRL-4G"
#define SCAN_TRIAL_HARDWARE_REV          "A01"

#define SCAN_TRIAL_SOFTWARE_VERSION_CODE "SW-SCAN-IRRIGATION-CONTROL-v0.2.0"
#define SCAN_TRIAL_SOFTWARE_NAME         "SCAN-IRR-CTRL-4G-A01 v0.2.0"
#define SCAN_TRIAL_SOFTWARE_FAMILY       "SCAN-IRRIGATION-CONTROL"
#define SCAN_TRIAL_SOFTWARE_VERSION      "0.2.0"

#endif /* SCAN_TRIAL_DEFS_H */
